### PR TITLE
staging: Huffmate V1.1

### PR DESCRIPTION
**Pull request by refcell**
## Changelog

- `JumpTableUtil` Optimizations in #70 by @clabby 
- SendEthers Utility in #73 by @abigger87 
- BitPackLib Improvements in #74 by @kadenzipfel 
- SafeMath Improvements in #75 by @MathisGD 
- ECDSA impl in #77 by @clabby 
- Update LibBit Nomenclature in #78 by @clabby 
- SafeTransferLib Optimizations in #81 by @abigger87 
-  Fix huffconfig address #88 by @MerlinEgalite 
- 3D storage mappings https://github.com/pentagonxyz/huffmate/pull/93 by @goncaloMagalhaes 
- Fix NonMatchingSelector tests https://github.com/pentagonxyz/huffmate/pull/94 by @AmadiMichael 
- Fix ternary tests and optimize TERNARY macro https://github.com/pentagonxyz/huffmate/pull/97 by @d1ll0n 
- feat: Bytes in #76 by @iFrostizz 
- fix: ERC20 main macro by @AmadiMichael

### CODE REVIEW

**Comment by devtooligan** [comment]
closing this pr as all these prs have been merged

**Comment by devtooligan** [comment]
@refcell @clabby Lets merge this!

**Review by devtooligan — APPROVED** [review]
lfg

**Review by cheethas — APPROVED** [review]
ya haw

**Comment by devtooligan** [comment]
🚀

**Comment by iFrostizz** [comment]
Send it 🔥

**Comment by iFrostizz** [comment]
Send it 🔥

**Pull request merged**
