### PR TITLE
Fix huffconfig address

### PR DESCRIPTION
**Pull request by MerlinEgalite**
Ownable tests were not passing locally because the huffConfig address wasn't the correct one.

This is because this function:
https://github.com/huff-language/foundry-huff/blob/eb9ea316389e8bd580f92908b8454399401d0316/src/HuffDeployer.sol#L10-L12
returns a new HuffConfig each it's called. For a long-term fix I would propose to apply the library to a config contract instead of creating one each time a function from the lib is called.

Here is a similar issue: https://github.com/huff-language/foundry-huff/pull/24

### CODE REVIEW

**Review by MathisGD — APPROVED** [review]
LGTM

Otherwise, you could use [set_broadcast](https://github.com/huff-language/foundry-huff/pull/22), which would put `msg.sender` as owner.

**Comment by devtooligan** [comment]
this should prob be merged, but we need to figure out if we are still using the `dev` branch or not.

asked this question in the `core` discord channel, so lets hold off on merging anything until we reach a decision on the `dev` branch

**Review by devtooligan — DISMISSED** [review]
lgtm

**Comment by devtooligan** [comment]
merging to `dev` this will likely be the last merge to dev then we will merge to main after this

**Review by devtooligan — APPROVED** [review]
lgtm

**Pull request merged**
